// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Context;

namespace PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Migrations
{
    [DbContext(typeof(InmobiliariaDatabaseContext))]
    partial class InmobiliariaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantMeses")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("FotoPropiedadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdPropiedad");

                    b.HasIndex("Usuario");

                    b.ToTable("PropiedadAlquiler");
                });

            modelBuilder.Entity("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("FotoPropiedadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdPropiedad");

                    b.HasIndex("Usuario");

                    b.ToTable("PropiedadVenta");
                });

            modelBuilder.Entity("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler", b =>
                {
                    b.HasOne("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("Usuario");
                });

            modelBuilder.Entity("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta", b =>
                {
                    b.HasOne("PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
